Improve CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,10 +13,68 @@ permissions:
   contents: read
   statuses: write
 
+env:
+  CR_REPO: rpm-software-management/createrepo_c
+  CR_VERSION: 0.15.11
+
 jobs:
+  BuildCreaterepo:
+    name: BuildCreaterepo
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Cache createrepo_c binary
+        uses: actions/cache@v3
+        id: createrepo-bin-cache
+        with:
+          path: ~/.cache/bin/createrepo_c
+          key: ${{runner.os}}-ek-rep-createrepoc-${{env.CR_VERSION}}
+
+      - name: Install build dependencies
+        if: steps.createrepo-bin-cache.outputs.cache-hit != 'true'
+        run: |
+          sudo apt-get update
+          sudo apt install -y libcurl4-openssl-dev \
+                              libbz2-dev libxml2-dev \
+                              libssl-dev zlib1g-dev \
+                              pkg-config \
+                              libglib2.0-dev \
+                              liblzma-dev \
+                              libsqlite0-dev \
+                              libsqlite3-dev \
+                              librpm-dev \
+                              libzstd-dev \
+                              python3.9-dev \
+                              cmake
+
+      - name: Build createrepo_c binary
+        if: steps.createrepo-bin-cache.outputs.cache-hit != 'true'
+        run: |
+          git clone --depth=1 --branch="${{env.CR_VERSION}}" \
+                    "https://github.com/${{env.CR_REPO}}.git" createrepo_c
+
+          cd createrepo_c
+          mkdir build
+          cd build
+
+          cmake .. -DWITH_ZCHUNK=NO -DWITH_LIBMODULEMD=NO -DENABLE_DRPM=OFF
+          make -j 1
+
+          mkdir -p ~/.cache/bin/
+
+          cp src/createrepo_c "$HOME/.cache/bin/"
+
+      - name: Update PATH
+        run: echo "$HOME/.cache/bin" >> $GITHUB_PATH
+
+      - name: Print createrepo_c version info
+        run: createrepo_c --version
+
   Go:
     name: Go
     runs-on: ubuntu-latest
+
+    needs: BuildCreaterepo
 
     env:
       SRC_DIR: src/github.com/${{ github.repository }}
@@ -26,6 +84,25 @@ jobs:
         go: [ '1.17.x', '1.18.x' ]
 
     steps:
+      - name: Restore createrepo_c binary from cache
+        uses: actions/cache@v3
+        id: createrepo-bin-cache
+        with:
+          path: ~/.cache/bin/createrepo_c
+          key: ${{runner.os}}-ek-rep-createrepoc-${{env.CR_VERSION}}
+
+      - name: Check cache restore
+        if: steps.createrepo-bin-cache.outputs.cache-hit != 'true'
+        run: |
+          echo "Can't restore createrepo_c binary from cache"
+          exit 1
+
+      - name: Update PATH
+        run: echo "$HOME/.cache/bin" >> $GITHUB_PATH
+
+      - name: Print createrepo_c version info
+        run: createrepo_c --version
+
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
